name: Build and Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting and formatting
        run: |
          npm run lint
          npm run prettier

      - name: Build site
        run: npm run build

      - name: Check build output
        run: |
          if [ ! -d "_site" ]; then
            echo "Error: _site directory not found"
            exit 1
          fi
          if [ ! -f "_site/index.html" ]; then
            echo "Error: index.html not found in _site"
            exit 1
          fi
          echo "✅ Build validation successful"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: "gh-pages"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
